# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Storybook to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - name: Codecov
      uses: codecov/codecov-action@v1.1.0
      with:
        token: 964600bd-f64d-4ebf-90ff-6b0cc6d6d604
        directory: ./coverage
    - run: npm run build-storybook
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: ./storybook-static
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
